version: '2'

volumes:
    elasticsearch_data: {}
    elasticsearch_log: {}
    kibana_log: {}

services:
  elasticsearch:
    image: akinaru/docker-elasticsearch-shield:latest
    container_name: elasticsearch
    command: elasticsearch
    restart: always
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/shield/keystore.jks:/usr/share/elasticsearch/config/shield/keystore.jks
      - elasticsearch_data:/usr/share/elasticsearch/data
      - elasticsearch_log:/var/log/elasticsearch
    ports:
      - "9200:9200"
    environment:
      - LOGSTASH_USER_NAME=${ES_LOGSTASH_USER_NAME}
      - LOGSTASH_PWD=${ES_LOGSTASH_USER_NAME}
      - KIBANA_ADMIN_USER_NAME=${ES_KIBANA_ADMIN_USER_NAME}
      - KIBANA_PWD=${ES_KIBANA_PWD}
      - KIBANA_USER_NAME=${ES_KIBANA_USER_NAME}
      - KIBANA_USER_PWD=${ES_KIBANA_USER_PWD}
  kibana:
    image: tzoratto/kibana-shield
    container_name: kibana
    restart: always
    command: kibana
    ports:
      - "5601:5601"
    volumes:
      - ./kibana:/opt/kibana/config
      - ./key:/etc/key
      - kibana_log:/var/log/kibana